// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CollisionDetect

struct PointData
{
    float3 pPos;
    bool isCollision;   // 1 Byte
};
// RWTexture2D<float4> Result;

float3 PanelPos;
float3 PanelNormal;
float3 objVelocity;
float3 objW;

float3x3 worldTrans;
float3x3 qMatrix;

RWStructuredBuffer<PointData> cPoint;

[numthreads(1,1,1)]
void CollisionDetect (uint3 id : SV_DispatchThreadID)
{
    PointData thePoint  = cPoint[id.x];
    float3 vertPos      = thePoint.pPos;
    float3 xi           = mul(worldTrans, vertPos);
    float sdf           = dot(xi - PanelPos,PanelNormal);

    uint cCounter       = 0;
    float3 avgPoint     = float3(0.0f, 0.0f, 0.0f);

    if (sdf < 0.0f)
    {
        float3 Rri = mul(qMatrix, vertPos);
        float3 vi = objVelocity + cross(objW, Rri);
        float viDotN = dot(vi,PanelNormal);
        if(viDotN < 0.0f)
        {
            thePoint.isCollision = true;
            avgPoint += thePoint.pPos;
            cCounter += 1; 
        }
    }
    cPoint[id.x] = thePoint;
}